# Use JDK image
FROM eclipse-temurin:21-jdk-alpine

# Set working directory
WORKDIR /app

# Copy Maven wrapper and pom
COPY pom.xml mvnw ./
COPY .mvn/ .mvn/

# Copy source code
COPY src/ src/

# Give execute permission to mvnw
RUN chmod +x ./mvnw

# Build the project
RUN ./mvnw package -DskipTests

# Expose port if needed (Spring Boot default)
EXPOSE 8080

# Run the jar
CMD ["java", "-jar", "target/BookStore-0.0.1-SNAPSHOT.jar"]