# Base image
FROM eclipse-temurin:21-jdk-alpine

# Workdir
WORKDIR /app

# Copy pom + source
COPY ./pom.xml ./ 
COPY ./src ./src

# Build the project
RUN ./mvnw package -DskipTests

# Run the jar
CMD ["java", "-jar", "target/BookStore-0.0.1-SNAPSHOT.jar"]